vaadin.launch-browser=true
spring.application.name=demo

# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
# 'create-drop' crea las tablas al iniciar y las elimina al cerrar la sesión
spring.jpa.hibernate.ddl-auto=create-drop

# Muestra las consultas SQL en la consola (útil para depuración)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect