vaadin.launch-browser=true
spring.application.name=demo

# Configuraci�n de la conexi�n a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci�n de JPA / Hibernate
# 'create-drop' crea las tablas al iniciar y las elimina al cerrar la sesi�n
spring.jpa.hibernate.ddl-auto=create-drop

# Muestra las consultas SQL en la consola (�til para depuraci�n)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto espec�fico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect